worker_processes auto;

events {
    worker_connections 16384;
}

http {
    upstream java_backends {
        server java1:8080;
        server java2:8080;
        server java3:8080;
    }

    upstream go_backends {
        server go1:8080;
        server go2:8080;
        server go3:8080;
    }

    upstream python_backends {
        server python1:8080;
        server python2:8080;
        server python3:8080;
    }

    server {
        listen 8080;
        server_name _;

        location /api/java/ {
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_pass http://java_backends;
        }

        location /api/go/ {
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_pass http://go_backends;
        }

        location /api/python/ {
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_pass http://python_backends;
        }
    }
}
