worker_processes auto;
events { worker_connections 16384; }
http {
    upstream go_backend {
        server go1:8080;
        server go2:8080;
        server go3:8080;
    }
    upstream java_backend {
        server java1:8080;
        server java2:8080;
        server java3:8080;
    }
    upstream python_backend {
        server python1:8080;
        server python2:8080;
        server python3:8080;
    }

    server {
        listen 8080;

        location /api/go/ {
            proxy_pass http://go_backend;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
        }
        location /api/java/ {
            proxy_pass http://java_backend;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
        }
        location /api/python/ {
            proxy_pass http://python_backend;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
        }
        location = /health { return 204; }
    }
}
